nelmio_cors:
    defaults:
        #origin_regex: true
        allow_origin: ["http://localhost:3000"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        allow_headers: ["Content-Type", "Authorization"]
        # expose_headers: ["Content-Type", "Authorization"]
        allow_credentials: true
        #expose_headers: ["Link"]
        max_age: 3600
    paths:
        "^/api/":
            allow_origin: ["http://localhost:3000"]
            allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
            allow_headers: ["Content-Type", "Authorization"]
            allow_credentials: true
            max_age: 3600
